//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_Fusion_Task.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ITFusionEntities : DbContext
    {
        public ITFusionEntities()
            : base("name=ITFusionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Eexp_Rev_type> Eexp_Rev_type { get; set; }
        public virtual DbSet<IT_Expenses_Revenues> IT_Expenses_Revenues { get; set; }
    }
}
