//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_Fusion_Task.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eexp_Rev_type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Eexp_Rev_type()
        {
            this.IT_Expenses_Revenues = new HashSet<IT_Expenses_Revenues>();
        }
    
        public int id_ex_re { get; set; }
        public string ex_re_type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IT_Expenses_Revenues> IT_Expenses_Revenues { get; set; }
    }
}
